version: '3.9'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nikulpharma
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/nikulpharma
      - PORT=4000
    depends_on:
      - db
    ports:
      - "4000:4000"

volumes:
  db_data:


